blog/urls.py
from django.conf.urls import url
from . import views

app_name = 'blog'
urlpatterns = [
	url(r'^$', views.PostView.as_view(), name='post_list'),
    # url(r'^$', views.post_list, name='post_list'),
    url(r'^post/(?P<pk>\w+)/$', views.PostDetailView.as_view(), name='post_detail'),
    # url(r'^post/(?P<pk>\w+)/$', views.post_detail, name='post_detail'),
    url(r'^postnew/$', views.PostNewView.as_view(), name='post_new'),
    # url(r'^postnew/$', views.post_new, name='post_new'),
    url(r'^post/(?P<pk>\w+)/edit/$', views.PostEditView.as_view(), name='post_edit'),
	# url(r'^post/(?P<pk>\w+)/edit/$', views.post_edit, name='post_edit'),
	url(r'^post/(?P<pk>\w+)/delete/$', views.PostDeleteView.as_view(), name='post_delete'),
	# url(r'^post/(?P<pk>\w+)/delete/$', views.post_delete, name='post_delete'),
]

blogproject/urls.py
from django.contrib import admin
from django.conf.urls import url, include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls')),
    url(r'', include('comments.urls')),
]

comments/urls.py
from django.conf.urls import url
from . import views

app_name = 'comments'
urlpatterns = [
	url(r'^comment/post/(?P<post_pk>\w+)/$', views.PostCommentView.as_view(), name='post_comment'),
    # url(r'^comment/post/(?P<post_pk>\w+)/$', views.post_comment, name='post_comment'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone

class Category(models.Model):
    """
    Django 要求模型必须继承 models.Model 类。
    Category 只需要一个简单的分类名 name 就可以了。
    CharField 指定了分类名 name 的数据类型，CharField 是字符型，
    CharField 的 max_length 参数指定其最大长度，超过这个长度的分类名就不能被存入数据库。
    当然 Django 还为我们提供了多种其它的数据类型，如日期时间类型 DateTimeField、整数类型 IntegerField 等等。
    Django 内置的全部类型可查看文档：
    https://docs.djangoproject.com/en/1.10/ref/models/fields/#field-types
    """
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Tag(models.Model):
    """
    标签 Tag 也比较简单，和 Category 一样。
    再次强调一定要继承 models.Model 类！
    """
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Post(models.Model):
    """
    文章的数据库表稍微复杂一点，主要是涉及的字段更多。
    """
    # def __init__(self, *initial_data, **kwargs):
    #     for dictionary in initial_data:
    #         for key in dictionary:
    #             setattr(self, key, dictionary[key])
    #     for key in kwargs:
    #         setattr(self, key, kwargs[key])

    # 文章标题
    title = models.CharField(max_length=70)

    # 文章正文，我们使用了 TextField。
    # 存储比较短的字符串可以使用 CharField，但对于文章的正文来说可能会是一大段文本，因此使用 TextField 来存储大段文本。
    body = models.TextField()

    # 这两个列分别表示文章的创建时间和最后一次修改时间，存储时间的字段用 DateTimeField 类型。
    pub_time = models.DateTimeField(default=timezone.now)
    update_time = models.DateTimeField(blank=True, null=True)

    # 文章摘要，可以没有文章摘要，但默认情况下 CharField 要求我们必须存入数据，否则就会报错。
    # 指定 CharField 的 blank=True 参数值后就可以允许空值了。
    abstract = models.CharField(max_length=200, blank=True)

    # 这是分类与标签，分类与标签的模型我们已经定义在上面。
    # 我们在这里把文章对应的数据库表和分类、标签对应的数据库表关联了起来，但是关联形式稍微有点不同。
    # 我们规定一篇文章只能对应一个分类，但是一个分类下可以有多篇文章，所以我们使用的是 ForeignKey，即一对多的关联关系。
    # 而对于标签来说，一篇文章可以有多个标签，同一个标签下也可能有多篇文章，所以我们使用 ManyToManyField，表明这是多对多的关联关系。
    # 同时我们规定文章可以没有标签，因此为标签 tags 指定了 blank=True。
    # 如果你对 ForeignKey、ManyToManyField 不了解，请看教程中的解释，亦可参考官方文档：
    # https://docs.djangoproject.com/en/1.10/topics/db/models/#relationships
    category = models.CharField(max_length=50, blank=True)
    # category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, default=1)
    # tags = models.ManyToManyField(Tag, blank=True)

    # 文章作者，这里 User 是从 django.contrib.auth.models 导入的。
    # django.contrib.auth 是 Django 内置的应用，专门用于处理网站用户的注册、登录等流程，User 是 Django 为我们已经写好的用户模型。
    # 这里我们通过 ForeignKey 把文章和 User 关联了起来。
    # 因为我们规定一篇文章只能有一个作者，而一个作者可能会写多篇文章，因此这是一对多的关联关系，和 Category 类似。
    # author = models.ForeignKey(User, on_delete=models.CASCADE)
    author = models.CharField(max_length=20)

    def to_dict(self):
        post_dict = {}
        post_dict['title'] = self.title
        post_dict['abstract'] = self.abstract
        post_dict['body'] = self.body
        post_dict['author'] = self.author
        post_dict['category'] = self.category
        return post_dict

    def save(self, *args, **kwargs):
        self.update_time = timezone.now()
        return super(Post, self).save(*args, **kwargs)

    def publish(self):
        self.update_time = timezone.now()
        self.save()

    def __str__(self):
        return self.title

    # def get_absolute_url(self):
    #     return reverse('blog:post_detail', kwargs={'pk': self.pk})

blog/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
	required_css_class = 'required'

	class Meta:
		model = Post
		fields = ('title', 'abstract', 'body', 'author', 'category',)

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from .models import Post, Tag, Category
from .forms import PostForm
from .httphelp import getPostList, getPostDetail, postPostDetail, putPostDetail, deletePostDetail
import json
from comments.forms import CommentForm
from django.views.generic import ListView, DetailView, TemplateView
from django.views.generic.edit import FormView, DeleteView
from django.views.generic.base import RedirectView
from django.urls import reverse

# Create your views here.
"""
def post_list(request):
    # post_list = Post.objects.all().order_by('-created_time')
    post_list = getPostList()
    return render(request, 'blog/post_list.html', context={'post_list': post_list})
"""

class PostView(ListView):
    # model = Post
    template_name = 'blog/post_list.html'
    context_object_name = 'post_list'

    def get_queryset(self):
    	# cate = get_object_or_404(Category, pk=self.kwargs.get('pk'))
        # return super(CategoryView, self).get_queryset().filter(category=cate)
        return getPostList()

"""
def post_detail(request, pk):
    # post = get_object_or_404(Post, pk=pk)
	post = getPostDetail(pk=pk)
	# post_ob = Post(title=post['title'], abstract=post['abstract'], body=post['body'], author=post['author'], category=post['category'], pub_time=post['pub_time'], update_time=post['update_time'], pk=post['pk'])

	# 记得在顶部导入 CommentForm
	form = CommentForm()
	# 获取这篇 post 下的全部评论
    # comment_list = post.comment_set.all()
	comment_list = post.get('comments')

	# 将文章、表单、以及文章下的评论列表作为模板变量传给 detail.html 模板，以便渲染相应数据。
	context	=	{'post': post,
				'form': form,
				'comment_list': comment_list
				}
	return render(request, 'blog/post_detail.html', context=context)
	# return render(request, 'blog/post_detail.html', context={'post': post})
"""

class PostDetailView(DetailView):
    # 这些属性的含义和 ListView 是一样的
    # model = Post
    template_name = 'blog/post_detail.html'
    context_object_name = 'post'
    """
    def get(self, request, *args, **kwargs):
        # 覆写 get 方法的目的是因为每当文章被访问一次，就得将文章阅读量 +1
        # get 方法返回的是一个 HttpResponse 实例
        # 之所以需要先调用父类的 get 方法，是因为只有当 get 方法被调用后，
        # 才有 self.object 属性，其值为 Post 模型实例，即被访问的文章 post
        response = super(PostDetailView, self).get(request, *args, **kwargs)

        # 将文章阅读量 +1
        # 注意 self.object 的值就是被访问的文章 post
        self.object.increase_views()

        # 视图必须返回一个 HttpResponse 对象
        return response
    """

    def get_object(self, queryset=None):
        # 覆写 get_object 方法的目的是因为需要对 post 的 body 值进行渲染
        # post = super(PostDetailView, self).get_object(queryset=None)
        post = getPostDetail(pk=self.kwargs.get('pk'))
        return post

    def get_context_data(self, **kwargs):
        # 覆写 get_context_data 的目的是因为除了将 post 传递给模板外（DetailView 已经帮我们完成），
        # 还要把评论表单、post 下的评论列表传递给模板。
        context = super(PostDetailView, self).get_context_data(**kwargs)
        form = CommentForm()
        comment_list = context['post'].get('comments')
        context.update({
            'form': form,
            'comment_list': comment_list
        })
        return context

"""
def post_new(request):
	if request.method == "POST":
		form = PostForm(request.POST)
		if form.is_valid():
			ori_post = form.save(commit=False)
			str_json = json.dumps(ori_post.to_dict())
			bytes = str_json.encode('utf-8')
			post = postPostDetail(bytes)
			# post = form.save()
			# post.author = request.user
			# post.save()
			# return redirect('blog:post_list')
			return redirect('blog:post_detail', pk=post['pk'])
	else:
		form = PostForm()
	return render(request, 'blog/post_edit.html', {'form': form})
"""

class PostNewView(FormView):
    template_name = 'blog/post_edit.html'
    form_class = PostForm

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        ori_post = form.save(commit=False)
        str_json = json.dumps(ori_post.to_dict())
        bytes = str_json.encode('utf-8')
        post = postPostDetail(bytes)
        return redirect('blog:post_detail', pk=post['pk'])
        # return super(PostNewView, self).form_valid(form)

"""
def post_edit(request, pk):
	# post = get_object_or_404(Post, pk=pk)
	post = getPostDetail(pk)
	post_ob = Post(title=post['title'], abstract=post['abstract'], body=post['body'], author=post['author'], category=post['category'], pub_time=post['pub_time'], update_time=post['update_time'], pk=post['pk'])
	if request.method == "POST":
		form = PostForm(request.POST, instance=post_ob)
		if form.is_valid():
			ori_post = form.save(commit=False)
			str_json = json.dumps(ori_post.to_dict())
			bytes = str_json.encode('utf-8')
			post = putPostDetail(pk, bytes)
			# post = form.save()
			# post = form.save(commit=False)
			# post.author = request.user
			# post.save()
			return redirect('blog:post_detail', pk=post['pk'])
	else:
		form = PostForm(instance=post_ob)
	return render(request, 'blog/post_edit.html', {'form': form})
"""

class PostEditView(FormView):
	template_name = 'blog/post_edit.html'
	form_class = PostForm

	def form_valid(self, form):
		ori_post = form.save(commit=False)
		str_json = json.dumps(ori_post.to_dict())
		bytes = str_json.encode('utf-8')
		post = putPostDetail(pk=self.kwargs.get('pk'), data=bytes)
		return redirect('blog:post_detail', pk=post['pk'])

	def get_initial(self):
		"""
    	Returns the initial data to use for forms on this view.
    	"""
		post = getPostDetail(pk=self.kwargs.get('pk'))
		return post

"""
def post_delete(request, pk):
	deletePostDetail(pk)
	return redirect('blog:post_list')
"""
class PostDeleteView(RedirectView):
	def get_redirect_url(self, *args, **kwargs):
		deletePostDetail(pk=self.kwargs.get('pk'))
		return reverse('blog:post_list')

templates/blog/post_detail.html
{% extends 'base.html' %}
{% block main %}
    <article class="post post-{{ post.pk }}">
        <header class="entry-header">
            <h1 class="entry-title">{{ post.title }}</h1>
            <div class="entry-meta">
                <span class="post-category"><a href="#">{{ post.category }}</a></span>
                <span class="post-date"><a href="#"><time class="entry-date"
                                                          datetime="{{ post.pub_time }}">{{ post.pub_time }}</time></a></span>
                <span class="post-author"><a href="#">{{ post.author }}</a></span>
                <span class="comments-link"><a href="#">{{ comment_list|length }} comments</a></span>
                <!-- <span class="views-count"><a href="#">555 閱讀</a></span> -->
                <a class="btn btn-default" href="{% url 'blog:post_edit' pk=post.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
                <a class="btn btn-default" href="{% url 'blog:post_delete' pk=post.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
            </div>
        </header>
        <div class="entry-content clearfix">
            {% if post.abstract %}
                <p>Abstract: <br/> {{ post.abstract|linebreaks }}</p><br/>
            {% endif %}
            <p>Content: <br/> {{ post.body|linebreaks }}</p>
        </div>
    </article>
    <section class="comment-area" id="comment-area">
        <hr>
        <h3>Add a comment</h3>
        <form action="{% url 'comments:post_comment' post.pk %}" method="post" class="comment-form">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-4">
                    <label for="{{ form.name.id_for_label }}" class="required">Name</label>
                    {{ form.name }}
                    {{ form.name.errors }}
                </div>
                <div class="col-md-4">
                    <label for="{{ form.email.id_for_label }}" class="required">Email</label>
                    {{ form.email }}
                    {{ form.email.errors }}
                </div>
                <div class="col-md-4">
                    <label for="{{ form.url.id_for_label }}">URL</label>
                    {{ form.url }}
                    {{ form.url.errors }}
                </div>
                <div class="col-md-12">
                    <label for="{{ form.text.id_for_label }}" class="required">Comment</label>
                    {{ form.text }}
                    {{ form.text.errors }}
                    <button type="submit" class="comment-btn">Submit</button>
                </div>
            </div>    <!-- row -->
        </form>
        <div class="comment-list-panel">
            <h3>Comment List | Total: <span>{{ comment_list|length }}</span> comments</h3>
            <ul class="comment-list list-unstyled">
                {% for comment in comment_list %}
                    <li class="comment-item">
                        <span class="nickname">{{ comment.name }}</span>
                        <time class="submit-date">{{ comment.created_time }}</time>
                        <span class="email"> {{ comment.email}}</span>
                        <span class="url"> {{comment.url}}</span>
                        <div class="text">
                            {{ comment.text|linebreaks }}
                        </div>
                    </li>
                {% empty %}
                <I>No comment</I>
                {% endfor %}
            </ul>
        </div>
    </section>
{% endblock main %}
{% block toc %}
    <div class="widget widget-content">
        <h3 class="widget-title">文章目錄</h3>
        <ul>
            <li>
                <a href="#">課程特點</a>
            </li>
            <!-- <li>
                <a href="#">谁适合这个教程</a>
            </li> -->
            <li>
                <a href="#">線上預覽</a>
            </li>
            <li>
                <a href="#">資源列表</a>
            </li>
            <li>
                <a href="#">獲取幫助</a>
            </li>
        </ul>
    </div>
{% endblock toc %}

templates/blog/post_edit.html
{% extends 'base.html' %}

{% block main %}
    <h1>New post</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

templates/blog/post_list.html
{% extends 'base.html' %}
{% block main %}
	{% for post in post_list %}
        <article class="post post-{{ post.pk }}">
            <header class="entry-header">
                <h1 class="entry-title">
                    <a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a>
                    <!-- <a href="＃">{{ post.title }}</a> -->
                </h1>
                <div class="entry-meta">
                    <span class="post-category"><a href="#">{{ post.category }}</a></span>
                    <span class="post-date"><a href="#"><time class="entry-date"
                                                              datetime="{{ post.pub_time }}">{{ post.pub_time }}</time></a></span>
                    <span class="post-author"><a href="#">{{ post.author }}</a></span>
                    <!-- <span class="comments-link"><a href="#">4 评论</a></span> -->
                    <!-- <span class="views-count"><a href="#">588 阅读</a></span> -->
                </div>
            </header>
            <div class="entry-content clearfix">
                <p>{{ post.abstract }}</p>
                <div class="read-more cl-effect-14">
                    <!-- <a href="＃" class="more-link">繼續閱讀<span class="meta-nav">→</span></a> -->
                    <a href="{% url 'blog:post_detail' pk=post.pk %}" class="more-link">繼續閱讀<span class="meta-nav">→</span></a>
                </div>
            </div>
        </article>
        {% empty %}
		<div class="no-post"><I>No article for now！</I></div>
	{% endfor %}
    <!-- 简单分页效果
    <div class="pagination-simple">
        <a href="#">上一页</a>
        <span class="current">第 6 页 / 共 11 页</span>
        <a href="#">下一页</a>
    </div>
    -->
    <!-- <div class="pagination">
        <ul>
            <li><a href="">1</a></li>
            <li><a href="">...</a></li>
            <li><a href="">4</a></li>
            <li><a href="">5</a></li>
            <li class="current"><a href="">6</a></li>
            <li><a href="">7</a></li>
            <li><a href="">8</a></li>
            <li><a href="">...</a></li>
            <li><a href="">11</a></li>
        </ul>
    </div> -->
{% endblock main %}