blog/urls.py
from django.conf.urls import url
from . import views

app_name = 'blog'
urlpatterns = [
	url(r'^$', views.PostView.as_view(), name='post_list'),
    # url(r'^$', views.post_list, name='post_list'),
    url(r'^post/(?P<pk>\w+)/$', views.PostDetailView.as_view(), name='post_detail'),
    # url(r'^post/(?P<pk>\w+)/$', views.post_detail, name='post_detail'),
    url(r'^postnew/$', views.PostNewView.as_view(), name='post_new'),
    # url(r'^postnew/$', views.post_new, name='post_new'),
    url(r'^post/(?P<pk>\w+)/edit/$', views.PostEditView.as_view(), name='post_edit'),
	# url(r'^post/(?P<pk>\w+)/edit/$', views.post_edit, name='post_edit'),
	url(r'^post/(?P<pk>\w+)/delete/$', views.PostDeleteView.as_view(), name='post_delete'),
	# url(r'^post/(?P<pk>\w+)/delete/$', views.post_delete, name='post_delete'),
]

blogproject/urls.py
from django.contrib import admin
from django.conf.urls import url, include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls')),
    url(r'', include('comments.urls')),
]

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title>Endless &amp; Ripple</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

    <!-- js -->
    <script src="{% static 'blog/js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'blog/js/pace.min.js' %}"></script>
    <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>
</head>

<body>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="/"><b>Endless</b> &amp; Ripple</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="/" data-hover="首頁">首頁</a></li>
                            <li class="cl-effect-11"><a href="/" data-hover="文章">文章</a></li>
                            <li class="cl-effect-11"><a href="/" data-hover="關於">關於</a></li>
                            <li class="cl-effect-11"><a href="/" data-hover="聯繫">聯繫</a></li>
                            <li class="cl-effect-11"><a href="{% url 'blog:post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="#">
                            <input type="search" placeholder="搜索" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>
<!-- <div class="copyrights">Collect from <a href="http://www.cssmoban.com/">Templates</a></div> -->
<!-- <div class="copyrights">Modified by <a href="http://zmrenwu.com/">追梦人物的博客</a></div> -->

<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
            	{% block main %}
                {% endblock main %}
            </main>
            <aside class="col-md-4">
                {% block toc %}
                {% endblock toc %}
                <div class="widget widget-recent-posts">
                    <h3 class="widget-title">最新文章</h3>
                    <ul>
                        <li>
                            <a href="#">Django 開發入門：前言</a>
                        </li>
                        <li>
                            <a href="#">Django Markdown 自動生成文章目錄</a>
                        </li>
                        <li>
                            <a href="#">Deploy Django Blog</a>
                        </li>
                    </ul>
                </div>
                <div class="widget widget-archives">
                    <h3 class="widget-title">歸檔</h3>
                    <ul>
                        <li>
                            <a href="#">2017 年 5 月</a>
                        </li>
                        <li>
                            <a href="#">2017 年 4 月</a>
                        </li>
                        <li>
                            <a href="#">2017 年 3 月</a>
                        </li>
                    </ul>
                </div>

                <div class="widget widget-category">
                    <h3 class="widget-title">分類</h3>
                    <ul>
                        <li>
                            <a href="#">Django Blog Courses <span class="post-count">(13)</span></a>
                        </li>
                        <li>
                            <a href="#">Python Courses <span class="post-count">(11)</span></a>
                        </li>
                        <li>
                            <a href="#">Django User Auth <span class="post-count">(8)</span></a>
                        </li>
                    </ul>
                </div>

                <div class="widget widget-tag-cloud">
                    <h3 class="widget-title">Tags</h3>
                    <ul>
                        <li>
                            <a href="#">Django</a>
                        </li>
                        <li>
                            <a href="#">Python</a>
                        </li>
                        <li>
                            <a href="#">Java</a>
                        </li>
                        <li>
                            <a href="#">筆記</a>
                        </li>
                        <li>
                            <a href="#">文檔</a>
                        </li>
                        <li>
                            <a href="#">AngularJS</a>
                        </li>
                        <li>
                            <a href="#">CSS</a>
                        </li>
                        <li>
                            <a href="#">JavaScript</a>
                        </li>
                        <li>
                            <a href="#">Snippet</a>
                        </li>
                        <li>
                            <a href="#">jQuery</a>
                        </li>
                    </ul>
                </div>
                <div class="rss">
                    <a href=""><span class="ion-social-rss-outline"></span> RSS 訂閱</a>
                </div>
            </aside>
        </div>
    </div>
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2017 - Collect From<a href="http://www.cssmoban.com/"
                                                        target="_blank" title="模板之家">模板之家</a>
                    - 由<a href="/" title="网页模板" target="_blank">追風的怪客</a>修改
                </p>
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="/">首頁</a></li>
            <li><a href="/">文章</a></li>
            <li><a href="/">關於</a></li>
            <li><a href="/">聯繫</a></li>
        </ul>
    </nav>
</div>

<script src="{% static 'blog/js/script.js' %}"></script>

</body>
</html>